name: Backend Tests

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unihub_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd Backend
        npm ci
      
    - name: Create .env file
      run: |
        cd Backend
        echo "PORT=3000" >> .env
        echo "NODE_ENV=test" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_NAME=unihub_test_db" >> .env
        echo "JWT_SECRET=test_secret" >> .env
        echo "JWT_EXPIRES_IN=1h" >> .env
        
    - name: Run database migrations
      run: |
        cd Backend
        npm run migrate
      
    - name: Run tests
      run: |
        cd Backend
        npm test 